# version: '3'

# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile_DEV
#     ports:
#       - "80:8000"
#     volumes:
#       - ./:/app/DevOps_Project
#       - data:/app/DevOps_Project/data
    
#   volumes:
#     data:/app/data


# version: "3.9"
   
# services:
#   db:
#     image: nouchka/sqlite3:latest
#     volumes:
#       - ./data/db:/root/db
#     environment:
#       - SQLITE3_DB=db.sqlite3
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "80:8000"
#     depends_on:
#       - db


# new experiment
# version: '3.7'

# services:
#   django_gunicorn:
#     volumes:
#       - static:/static
#     env_file:
#       - .env
#     build:
#       context: .
#     ports:
#       - "8000:8000"
#   nginx:
#     build: ./nginx
#     volumes:
#       - static:/static
#     ports:
#       - "80:80"
#     depends_on:
#       - django_gunicorn

# volumes:
#   static:


# version: "3.9"
   
# services:
#   db:
#     image: nouchka/sqlite3:latest
#     volumes:
#       - ./data/db:/root/db
#     environment:
#       - SQLITE3_DB=db.sqlite3
#   web:
#     build: .
#     command: python3.9 manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db


# web:
#   build: .
#   environment:
#     MYENV: venv
#   volumes:
#     - .:/code
# web_migrate:
#   extends:
#     service: web
#   command: python manage.py migrate
# web_run:
#   extends:
#     service: web
#   command: python manage.py runserver 0.0.0.0:8000
#   ports:
#     - "8000:8000"


version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3