# Generated by Django 4.2.6 on 2023-10-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=10)),
                ('l_name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Veg_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('category', models.CharField(default='', max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='static/images')),
            ],
        ),
    ]
