# Generated by Django 4.2.6 on 2023-10-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Veg_Item',
            new_name='Categories',
        ),
    ]
