# Generated by Django 4.2.6 on 2023-10-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_App', '0002_rename_veg_item_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
